<?php

/*
 * Hook presave on issue nodes.
 */
function pdf_imagefield_preview_generator_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

	switch ($op) {
		case 'presave':
			if($node->type == 'issue') {
				generatePdfImagePreviews($node);
				// print_r($node);
				// die();
			}
		break;
		
		case 'update':
				if($node->type == 'issue') {
				// print_r($node);
				// die();
			}
		break;
			
	}

}


/*
* Disable display of the field_issuecover field. This could lead to problems later, but will simplify the process for now.
*/
function pdf_imagefield_preview_generator_form_alter(&$form, $form_state, $form_id) {
	if (isset($form['type']) && isset($form['#node'])) {
		if ($form_id === 'issue_node_form') {
			$form['field_issuecover']['#prefix'] = '<div style="display:none;">';
			$form['field_issuecover']['#suffix'] = '</div>';
		}
	}
}


/*
 * Functions Below to generate jpg previews of PDF nodes and store them in a CCK imagefield.
 * This is a quick function and should really have menu selections to choose source
 * and target fields.
 * 
 * A bit of this stolen from 'PDF to ImageField' module.
 */


/*
 * Return source and target CCK fields.
 * FOR NOW : Source and target CCK fields are Hardcoded here. Use is SOURCE=>TARGET
 * In future, would be great to have selected through admin menu.
 */
function generateSourceTargetArray() {
	$returnArray=array(
		"field_fullissuepdf" => "field_issuecover",
	);

	return($returnArray);
}


/*
 * Generate the jpg files and insert into node here.
 */
function generatePdfImagePreviews(&$node) {

	//print_r($node->field_fullissuepdf);
	// print_r($node);
	// die('');
	// if ($node->field_fullissuepdf[0]['status']=='1') {

	$arrayOfPreviews=array();
	$arrayOfPreviews=generateSourceTargetArray();

	foreach ($arrayOfPreviews as $sourceField => $targetField) {

		$sourcePdfFileId=$node->{$sourceField}[0]['fid'];
		$sourcePdfFileObject=field_file_load($sourcePdfFileId);
		$sourcePdfFilePath=$sourcePdfFileObject['filepath'];

		// If it exists, Delete file from DB for this pdf.
		file_delete(str_replace('.pdf','.jpg',$sourcePdfFilePath));
		
		$targetImageField=$targetField;

		$convertedFilePath=generatePdfFirstPageImage($sourcePdfFilePath,str_replace('.pdf','.jpg',$sourcePdfFilePath));

		if ($convertedFilePath == FALSE) {
			watchdog('pdf to image: imageapi imagemagick', '!errors', array('!errors' => $errors_txt), WATCHDOG_ERROR);
		} else {
			if ($node->field_issuecover[0]['filepath']!=$convertedFilePath) {

				// New Image Insert Needed, Do rest of processing here.
				$imageToInsert = new stdClass();
				// $imageToInsert->filename = str_replace('.pdf','.jpg',$sourcePdfFileObject['filename']);
				$imageToInsert->filename = basename($convertedFilePath);
				$imageToInsert->filepath = $convertedFilePath;
				$imageToInsert->filemime = file_get_mimetype($imageToInsert->filepath);
				$imageToInsert->filesize = filesize($imageToInsert->filepath);
				$imageToInsert->status = 1;
				$imageToInsert->timestamp = time();
				$imageToInsert->uid = 1;
				$imageToInsert->list=1;

				drupal_write_record('files', $imageToInsert);
				// Inform modules about the newly added file.
				module_invoke_all('file_insert', $imageToInsert);
				module_invoke_all('entity_insert', $imageToInsert, 'file');

				file_set_status($imageToInsert, FILE_STATUS_PERMANENT);
				$node->{$targetField}[0] = (array) $imageToInsert;
			} // end if filepath is already in DB that matches new jpg.
		} // end else convertedpath
	} // end foreach arrayofpreviews
} 



/*
 * Function to convert PDF into jpg thumbnail of first page only.
 */
function generatePdfFirstPageImage($source, $dest, $args = array(), $extra = array()) {

	$d_arguments['quality'] = '-quality '. escapeshellarg(variable_get('imageapi_imagemagick_quality', 75));
	$command = implode(' ', $extra) .' '. escapeshellarg($source.'[0]') .' '. implode(' ', $args) .' '. escapeshellarg($dest);
	$returncommand=_imageapi_imagemagick_convert_exec($command, $output, $errors);

	if (0 != 0) {
		$errors_txt = '<pre>' . (is_array($errors) ? implode("\n", $errors) : $errors) . '</pre>';
		watchdog('pdf to image: imageapi imagemagick', '!errors', array('!errors' => $errors_txt), WATCHDOG_ERROR);
		return FALSE;
	}
	return ($dest);
}

?>
